// Middlewares for the sauce management

const Sauce = require ('../models/sauce'); // we import the sauce model

exports.createSauce = (req, res, next) => { // Middleware to create a new sauce
    const sauceObject = JSON.parse(req.body.sauce); // we take the datas of the body request in an object
    console.log(sauceObject)
    delete sauceObject._id; // we delete the automatic id generated by mongoose
    delete sauceObject._userId;
    const sauce = new Sauce ({ // we create the new sauce thanks to our sauce model and the datas of the body request
        ...sauceObject,
        userId: req.auth.userId,
        imageUrl: `${req.protocol}://${req.get("host")}/images/${ // we define the image url
			req.file.filename
		}`,
        likes: 0,
        dislike: 0
    });
    sauce.save() // we register the sauce in the data base
    .then(()=>res.status(201).json({message : "Nouvelle sauce générée !"})) // the ressource has been created and we send the info to the frontend
    .catch((error)=>res.status(400).json({error}));
};

exports.getAllSauces = (req, res, next) => {
	Sauce.find()
		.then((sauces) => res.status(200).json(sauces))
		.catch((error) => res.status(400).json({ error }));
};

